import Head from "next/head";
import styles from "../../styles/Index.module.css";

export default function Index({ articles }) {
  console.log("articles", articles);
  return (
    <section className="page_wrapper">
      <Head>
        <title>LandlordStudio recruitment test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dashboard</h1>
    </section>
  );
}
