import Head from "next/head";
import styles from "../../styles/Index.module.css";
import PaymentList from "../components/PaymentList";
import { Payment } from "../pages/data/payment";
import { server } from "../config/index";

export default function Index({ paymentList }) {
  return (
    <>
      <Head>
        <title>LandlordStudio recruitment test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PaymentList paymentList={paymentList} />
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/payments`);
  let paymentList: Payment[] = await res.json();
  // Payments should be listed in ascending chronological order (by Date).
  paymentList = paymentList.sort((a, b) => {
    let dateA = new Date(a.dueDate).getTime();
    let dateB = new Date(b.dueDate).getTime();
    return dateA > dateB ? 1 : -1;
  });

  return {
    props: {
      paymentList,
    },
  };
};
